os: linux
dist: focal

language: python
python:
- "3.7"
- "3.8"
- "3.9"
- "3.10"
- "pypy3"

env:
- DEBIAN_DEPS=true
- DEBIAN_DEPS=

addons:
  apt:
    packages:
    - libsodium23
    - libsodium-dev

install:
- python -m pip install --upgrade pip setuptools wheel
- python -m pip --version
- python -m pip install --upgrade pytest pytest-asyncio pylint flake8
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m pip install --upgrade mypy; fi
- if [   $DEBIAN_DEPS ]; then python -m pip install --upgrade cryptography==3.3.2 pydantic==1.7.4; fi
- if [ ! $DEBIAN_DEPS ]; then python -m pip install --upgrade cryptography        pydantic; fi
- python -m pip install .

script:
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m mypy --strict x3dh/; fi
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m mypy --strict tests/; fi
- if [ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]; then python -m mypy --strict setup.py; fi
- python -m pylint x3dh/
- python -m pylint tests/*.py
- python -m pylint setup.py
- python -m flake8 x3dh/
- python -m flake8 tests/*.py
- python -m flake8 setup.py
- python -m pytest
